### ISSUE TITLE
Setup - missing modules

### ISSUE THREAD

**Issue by alimon808** [editdata/editdata.org#68]
npm run bundle spits out attached error
[setup-missing-module-error.txt](https://github.com/editdata/editdata.org/files/190783/setup-missing-module-error.txt)

**Comment by sethvincent** [comment]
oh weird! i'll take a look.

error for later reference:

```
Error: Cannot find module './utils/classname' from 'C:\workspace\github\editdata.org\node_modules\data-form\node_modules\data-fields'
    at C:\workspace\github\editdata.org\node_modules\browserify\node_modules\resolve\lib\async.js:55:21
    at load (C:\workspace\github\editdata.org\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\workspace\github\editdata.org\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\workspace\github\editdata.org\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```
